plugins:
  axiom_disclosure_enabled:
    default: false
    client: true

  axiom_disclosure_silence_duration_hours:
    default: 24
    min: 0
    max: 720
    type: integer

  axiom_disclosure_export_dir:
    default: ""
    type: text

  axiom_disclosure_silence_reason:
    default: "Axiom safeguarding action"
    type: text

  axiom_disclosure_notification_email:
    default: ""
    type: text
